version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    tty: true
    ports:
      - "4200:3000"
    volumes:
      - ./:/api
  mysql:
    image: mysql:8.0
    ports:
      - '3336:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: template
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
    driver: local